name: Playwright Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  # Allow updating snapshots during manual runs
  workflow_call:
    inputs:
      update-snapshots:
        description: "Update snapshots?"
        type: boolean

  # Allow updating snapshots during automatic runs
  workflow_dispatch:
    inputs:
      update-snapshots:
        description: "Update snapshots?"
        type: boolean
jobs:
  playwright:
    name: 'Playwright tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    - name: Run type checks
      run: npx tsc -p tsconfig.json --noEmit
    - name: Set up cache
      id: cache
      uses: actions/cache@v4
      with:
        key: cache/${{github.repository}}/${{github.ref}}
        restore-keys: cache/${{github.repository}}/refs/heads/main
        path: .test/**
    - name: Initialize snapshots
      if: ${{steps.cache.outputs.cache-hit != 'true' || inputs.update-snapshots == 'true'}}
      run: npx playwright test --update-snapshots
    - name: Run Playwright tests
      continue-on-error: true
      run: npx playwright test
    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: .test/spec/results/
        retention-days: 30
        overwrite: true
