name: Playwright Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run type checks
      run: npx tsc -p tsconfig.json --noEmit
    - name: Set up cache
      id: cache
      uses: actions/cache@v4
      with:
        key: cache/${{github.repository}}/${{github.ref}}
        restore-keys: cache/${{github.repository}}/refs/heads/main
        path: .test/**
    - name: Initialize snapshots
      if: ${{steps.cache.outputs.cache-hit != 'true'}}
      run: npx playwright test --update-snapshots
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
